//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Login.Dsbd_css
{


    public partial class Bank_Reconciliation
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList ddlMode;
        protected global::System.Web.UI.WebControls.TextBox txtOpeningBalance;
        protected global::System.Web.UI.WebControls.TextBox txtTotalBalance;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox Particular;
        protected global::System.Web.UI.WebControls.TextBox Reference;
        protected global::System.Web.UI.WebControls.DropDownList ddlPayment_Type;
        protected global::System.Web.UI.WebControls.TextBox amt;
        protected global::System.Web.UI.WebControls.TextBox BankNametxt;
        protected global::System.Web.UI.WebControls.TextBox FTotal;
    }
}
