//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Login.Dsbd_css
{


    public partial class Expenses
    {
        protected global::System.Web.UI.WebControls.TextBox name;
        protected global::System.Web.UI.WebControls.TextBox date;
        protected global::System.Web.UI.WebControls.TextBox Payment_Mode;
        protected global::System.Web.UI.WebControls.TextBox amount;
        protected global::System.Web.UI.WebControls.GridView GridView1;
    }
}
