//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Login.Dsbd_css
{


    public partial class Purchase
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtProduct;
        protected global::System.Web.UI.WebControls.TextBox qty;
        protected global::System.Web.UI.WebControls.TextBox rate;
        protected global::System.Web.UI.WebControls.TextBox amt;
        protected global::System.Web.UI.WebControls.TextBox FGST;
        protected global::System.Web.UI.WebControls.TextBox FNet;
        protected global::System.Web.UI.WebControls.Label digitalClocklbl;
        protected global::System.Web.UI.WebControls.DropDownList ddlProduct_Name;
        protected global::System.Web.UI.WebControls.Label txtSuccess;
        /// <summary>
        /// quantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox quantity;

        /// <summary>
        /// purchaseButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button purchaseButton;
    }
}
