//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Login.Dsbd_css
{


    public partial class Sales_Invoice
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtDefaultDateTime;
        protected global::System.Web.UI.WebControls.Label Inv_Nolbl;
        protected global::System.Web.UI.WebControls.TextBox Inv1_Notxt;
        protected global::System.Web.UI.WebControls.TextBox Customer_Nametxt;
        protected global::System.Web.UI.WebControls.TextBox Addresstxt;
        protected global::System.Web.UI.WebControls.TextBox Citytxt;
        protected global::System.Web.UI.WebControls.Label digitalClocklbl;
        protected global::System.Web.UI.WebControls.TextBox Particular;
        protected global::System.Web.UI.WebControls.TextBox qty;
        protected global::System.Web.UI.WebControls.TextBox rate;
        protected global::System.Web.UI.WebControls.TextBox amt;
        protected global::System.Web.UI.WebControls.TextBox FTotal;
        protected global::System.Web.UI.WebControls.TextBox FGST;
        protected global::System.Web.UI.WebControls.TextBox FDisc;
        protected global::System.Web.UI.WebControls.TextBox FNet;
        protected global::System.Web.UI.WebControls.DropDownList ddlParticular;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;

    }
}
