//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Login.Dsbd_css
{


    public partial class service
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox Particular;
        protected global::System.Web.UI.WebControls.TextBox Deposit;
        protected global::System.Web.UI.WebControls.DropDownList paymentMethodDropDown;
        protected global::System.Web.UI.WebControls.TextBox amt;
        protected global::System.Web.UI.WebControls.TextBox Studenttxt;
        protected global::System.Web.UI.WebControls.TextBox Student_IDtxt;
        protected global::System.Web.UI.WebControls.TextBox branchDropDown;
        protected global::System.Web.UI.WebControls.TextBox Placetxt;
        protected global::System.Web.UI.WebControls.TextBox Course;
        protected global::System.Web.UI.WebControls.TextBox FTotal;
        protected global::System.Web.UI.WebControls.TextBox FRemaining;
        protected global::System.Web.UI.WebControls.TextBox paymentMethod;
        protected global::System.Web.UI.WebControls.TextBox txtTotal_Deposit;
        protected global::System.Web.UI.WebControls.TextBox txtRemaining;
        
    }

}
